This is makeindex, version 2.15 [MiKTeX 20.6.29].
Scanning style file ./Relatorio.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Relatorio.acn....done (58 entries accepted, 0 rejected).
Sorting entries....done (353 comparisons).
Generating output file Relatorio.acr....done (118 lines written, 0 warnings).
Output written in Relatorio.acr.
Transcript written in Relatorio.alg.
