This is makeindex, version 2.15 [MiKTeX 21.3].
Scanning style file ./Relatorio.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Relatorio.acn....done (85 entries accepted, 0 rejected).
Sorting entries....done (553 comparisons).
Generating output file Relatorio.acr....done (96 lines written, 0 warnings).
Output written in Relatorio.acr.
Transcript written in Relatorio.alg.
