###########################################################
#                                                         #
#                       MAKEFILE                          #
#                                                         #
###########################################################
CC = gcc
CXX = gcc

.PHONY: clean

clean:
	-rm -rf *.ind
	-rm -rf *.blg
	-rm -rf *.dvi
	-rm -rf *.idx
	-rm -rf *.aux
	-rm -rf *.log
	-rm -rf *.bbl
	-rm -rf *.ilg
	-rm -rf *.gz
	-rm -rf *.toc
	-rm -rf *.out
	-rm -rf *.lof
	-rm -rf *.md
	-rm -rf *.fls
	-rm -rf *.ps
	-rm -rf *.nav
	-rm .rf *.snm
